name: 'Setup Java with Maven Cache'
description: 'Sets up JDK with proper Maven dependency caching for faster builds'

inputs:
  java-version:
    description: 'Java version to setup'
    required: false
    default: '17'
  java-distribution:
    description: 'Java distribution'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK with Maven cache
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: 'maven'
    
    - name: Display cache info
      shell: bash
      run: |
        echo "✅ Java and Maven cache configured"
        echo "📦 Maven version: $(mvn -version | head -n 1)"
        echo "🔄 Maven dependencies are cached at ~/.m2/repository"
        echo "💡 Cache is shared across all workflow jobs"
        echo "🔑 Cache key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"

